version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    volumes:
      - ./schemas/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: DB
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '1234'
        MYSQL_ROOT_PASSWORD: '1234'